### ISSUE TITLE
大佬，在使用XL模型时报错😭

### ISSUE THREAD

**Issue by qlsf** [Van-wise/sd-colab#5]
报错代码:Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-5-f5466ebd2379>", line 39, in zip_outputs
    time.sleep(save_interval)
KeyboardInterrupt
^C
^C请问colab是不是不能运行太大的模型

**Comment by Van-wise** [comment]
从错误信息来看,是手动停止了代码运行。
sdxl模型无法直接使用,需要在模型管理处进行手动配置。
错误原因： 没有正确识别sdxl模型
解决方法：
模型管理器 - 选中sdxl模型 基地模型设置为xl config文件选中xl_base.yaml
参考：https://github.com/Van-wise/sd-colab/blob/main/Invoke/Invoke_bug%26fix.ipynb
